### PR TITLE
Dev denormalise

### PR DESCRIPTION
**Pull request by emaV**
* move normalisation to filter pipeline adding a new filter `normalise.js`
* set *normallise* as default filter
* add a plain filter `plain.js`

**TODO**
* FIX the test

### CODE REVIEW

**Comment by emaV** [comment]
* Solve #55 
* Solve #7

**Comment by philbooth** [comment]
Hey @emaV, thanks heaps for doing this. I still don't think it is the correct approach long-term, but as a first step towards deleting normalisation entirely, I can live with it.

As well as fixing the failing tests, there are a few other test-related changes that need making:

* New tests for the `plain` mapper.
* Move the tests for normalisation into a dedicated suite inside `tests/filters/normalise.js`.
* Mock out the `normalise` filter in `tests/index.js`. This is partly to quieten the warnings from mockery, but more importantly to better isolate that suite.

If you're unsure about some of those, no worries. I'm happy to chip in and help out by answering questions, writing tests or whatever is needed.

What do you think?

**Comment by emaV** [comment]
It sounds good to me!

I'm really not an expert on testing, quite a noob indeed, so I can't help very much on this.

**Comment by philbooth** [comment]
No probs. I can branch from your changes and get those bits finished off.

Might not happen until a bit later this week, it depends on when I can make the time.

**Comment by philbooth** [comment]
Hey @emaV, just to let you know these changes have now been published as version 3.0.0 on npm. Let me know if there are any issues. :)

**Comment by emaV** [comment]
Testing right now! So far so good.

So if and when the normalisation is needed it's just matter of include the js

    normalise = require('../normalise');

**Comment by philbooth** [comment]
Yep, that's it. I figured normalisation was semantically different to the filter step and it felt kind of out-of-place sticking it there.

Another nice side-effect of making the mappers opt-in to normalisation is that the unit tests for them now pass in raw boomerang-format data. So when removing normalisation, the tests themselves don't need to change. If they fail it is because of a genuine bug.

**Pull request merged**
