### PR TITLE
Add options for configuring SSL/TLS connection to beacon server

### PR DESCRIPTION
**Pull request by tollmanz**
This server should support a secure connection. This PR aims to bring in options for communicating via HTTPS using either SSL or TLS.

To do:

- [x] Add more TLS options
- [ ] Unit tests
  - [x] Modify existing tests to account for HTTPS options
  - [ ] Add tests of new features
- [ ] Add docs
- [ ] Add author

### CODE REVIEW

**Comment by philbooth** [comment]
Hey @tollmanz, how's it going?

I've got some free time coming and I'd like to do whatever is outstanding on this branch then get it released. Are you cool with that?

Looks like it is mostly going to be a case of resolving merge conflicts, then adding tests and documentation, does that sound about right to you?

**Comment by tollmanz** [comment]
@philbooth That is correct. I totally got stuck at the test implementation. I recently switched jobs and am not working on this project anymore :(

I would be happy to help, but finding time for getting the test stuff figured out is too much right now.

**Comment by philbooth** [comment]
No worries, I'm grateful that you made a start on it and contributed at all, thanks. :)

**Comment by tollmanz** [comment]
Whoa! Awesome @philbooth! No tests after all?

**Comment by philbooth** [comment]
No, there are tests, but I added them as part of a different pull request (#51) is all:

https://github.com/nature/boomcatch/blob/master/test/index.js#L1045

Sorry it took me so long to get round to this! :)

**Comment by tollmanz** [comment]
Got it! I was worried that there weren't any. I wanted to see what you did.

I'm psyched that this is in there!

**Comment by philbooth** [comment]
Ah, if you want to have a look at the tests, these ones are probably more interesting:

https://github.com/nature/boomcatch/blob/master/test/index.js#L3357

**Pull request merged**
