### PR TITLE
FIX millennium bug: by default qs will only parse up to 1000 parameters

### PR DESCRIPTION
**Pull request by emaV**

### CODE REVIEW

**Comment by philbooth** [comment]
Cool, thanks for this.

Before releasing, I might add a command-line option that lets the user set this themselves; it seems more reasonable than setting an arbitrary "big enough" one ourselves. Does that sound good to you?

**Comment by emaV** [comment]
Yes, seems a good idea to add as an option even thought probably 10k should
be enough for most cases.

**Comment by philbooth** [comment]
Actually, having read the source code for `qs`, I've changed my mind. I think we should always pass `Infinity` rather than a magic number of our own devising.

This is the relevant line in the `qs` code:

```js
var parts = str.split(options.delimiter, options.parameterLimit === Infinity ? undefined : options.parameterLimit);
```
(https://github.com/hapijs/qs/blob/master/lib/parse.js#L19)

Going to do that, unless you disagree?

**Comment by emaV** [comment]
Yeah, it makes sense to me. I suggested 10K as a conservative approach but in the end the code is parsing a POST payload so we don't have to worry about depth limits

> The depth limit helps mitigate abuse when qs is used to parse user input, and it is recommended to keep it a reasonably small number.

**Pull request merged**
